# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 22:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodues', '0002_auto_20161113_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel', models.CharField(choices=[(b'1', b'Manas'), (b'2', b'Siang'), (b'3', b'Subhansiri'), (b'4', b'Dhansiri'), (b'5', b'Dihing'), (b'6', b'Umiam'), (b'7', b'Barak'), (b'8', b'Kameng')], max_length=1)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrantClearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField()),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Borrower', to=settings.AUTH_USER_MODEL)),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeadOfDep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[(b'1', b'CSE'), (b'2', b'MnC'), (b'3', b'ECE'), (b'4', b'EEE'), (b'5', b'CL'), (b'6', b'CE'), (b'7', b'EP')], max_length=1)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[(b'1', b'B.Tech'), (b'2', b'M.Tech'), (b'3', b'P.hD'), (b'4', b'B.Des')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrative',
            name='department',
            field=models.CharField(choices=[(b'1', b'Library'), (b'2', b'CC'), (b'3', b'Online CC'), (b'4', b'Submit Thesis'), (b'5', b'Gymkhana'), (b'6', b'Assistant Registrar'), (b'7', b'Account')], max_length=1),
        ),
        migrations.AlterField(
            model_name='prof',
            name='department',
            field=models.CharField(choices=[(b'1', b'CSE'), (b'2', b'MnC'), (b'3', b'ECE'), (b'4', b'EEE'), (b'5', b'CL'), (b'6', b'CE'), (b'7', b'EP')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[(b'1', b'CSE'), (b'2', b'MnC'), (b'3', b'ECE'), (b'4', b'EEE'), (b'5', b'CL'), (b'6', b'CE'), (b'7', b'EP')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='hostel',
            field=models.CharField(choices=[(b'1', b'Manas'), (b'2', b'Siang'), (b'3', b'Subhansiri'), (b'4', b'Dhansiri'), (b'5', b'Dihing'), (b'6', b'Umiam'), (b'7', b'Barak'), (b'8', b'Kameng')], max_length=1),
        ),
        migrations.AlterField(
            model_name='warden',
            name='hostel',
            field=models.CharField(choices=[(b'1', b'Manas'), (b'2', b'Siang'), (b'3', b'Subhansiri'), (b'4', b'Dhansiri'), (b'5', b'Dihing'), (b'6', b'Umiam'), (b'7', b'Barak'), (b'8', b'Kameng')], max_length=1),
        ),
    ]
